function s=theta0_W0(S)
	dtheta		= S.dtheta;
	list1		= S.list1;
	list2		= S.list2;
	check1		= S.check1;
	check2		= S.check2;
	
	function sol=solution_best_W0(vm)
		% find W0 (halo mass) for a given theta0 - fast approximation
		s = model.tov.rar.bisect.W0(struct(...
			'model',			vm,...
			'solution',			S.solution,...
			'list',				list2,...
			'check_increase',	check2,...
			'dW',				dtheta,...
			'tau',				1E-8,...
			'iteration_number', 40 ...
		));

		sol = s.solution;
	end


	% same for theta0 (pass new s.model)
	s = model.tov.rar.bisect.theta0(struct(...
		'model',			S.model,...
		'solution',			@solution_best_W0,...
		'list',				list1,...
		'check_increase',	check1,...
		'dtheta',			dtheta,...
		'tau',				1E-6,...
		'iteration_number', 40 ...
	));
end