function [SOL,varargout] = W0(S)

% set inital vector X0 (model => nlinfit vector)
fVector = @(SOL) [
	SOL.data.W0
];



% set model wrapper (nlinfit vector => model)
fModel = @(b,SOL) struct(...
	'param', struct(...
		'beta0',	SOL.data.beta0,...
		'theta0',	SOL.data.theta0,...
		'W0',		b(1) ...
	),...
	'options',	S.model.options ...
);

% set argument struct
S = lib.struct.merge(struct(...
	'fVector',		fVector,...
	'fModel',		fModel ...
),S);

SOL				= lib.fitting.bisect(S);
varargout{1}	= S.fModel(S.fVector(SOL),SOL);