function [SOL,varargout] = m(S)

% set iteration print function
sPrec	= '%1.15e';
sStrong = ['<strong>' sPrec '</strong>'];
sFormat = strjoin({sStrong,'%1.3e\n'},'\t');
fLog	= @(model,SOL,list) fprintf(sFormat,SOL.data.m,list.chi2(SOL));

% set inital vector X0 (model => nlinfit vector)
fVector = @(SOL) [
	SOL.data.m
];



% set model wrapper (nlinfit vector => model)
fModel = @(b,SOL) struct(...
	'param', struct(...
		'm',		b(1),...
		'beta0',	SOL.data.beta0,...
		'theta0',	SOL.data.theta0,...
		'W0',		SOL.data.W0 ...
	),...
	'options',	S.model.options ...
);

SOL = model.tov.rar.quick(S.model);

% set argument struct
S = lib.struct.merge(struct(...
	'fVector',		fVector,...
	'fModel',		fModel,...
	'fSolution',	@(vm) SOL,...
	'debug',		fLog ...
),S);

SOL				= lib.fitting.nlinfit(S);
varargout{1}	= S.fModel(S.fVector(SOL),SOL);