function varargout = beta0(vm,list,varargin)
module.constraints

% set iteration print function
sPrec	= '%1.12e';
sStrong = ['<strong>' sPrec '</strong>'];
sFormat = strjoin({sPrec,sStrong,sPrec,sPrec,'%1.3e\n'},'\t');
fLog	= @(SOL) fprintf(sFormat,SOL.data.m/keVcc,SOL.data.beta0,SOL.data.theta0,SOL.data.W0,list.chi2(SOL));

% set chi2 function
fResponse = @(SOL) list.chi2(SOL);

% set update function
fUpdate = @(x,vm) struct(...
	'param', struct(...
		'm',		vm.param.m,...
		'beta0',	exp(x),...
		'theta0',	vm.param.theta0,...
		'W0',		vm.param.W0 ...
	),...
	'options', vm.options ...
);

% set model function
fModel = @(SOL) struct(...
	'param', struct(...
		'm',		SOL.data.m,...
		'beta0',	SOL.data.beta0,...
		'theta0',	SOL.data.theta0,...
		'W0',		SOL.data.W0 ...
	),...
	'options', vm.options ...
);

% set search interval
Xint(1) = vm.param.beta0*(1 - 2E-1);
Xint(2) = vm.param.beta0*(1 + 2E-1);

% search for solution
[varargout{1:nargout}] = model.tov.rar.gosect(vm,list,...
	'Xint',			log(Xint),...
	'fResponse',	fResponse,...
	'fModel',		fModel,...
	'fUpdate',		fUpdate,...
	'fLog',			fLog,...
	varargin{:} ...
);
